### ISSUE TITLE
metrics reader token returns 403 OpenShift Permissions Issue Post-Upgrade

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#4786]
Following the recent OpenShift upgrade, registry is experiencing a `403 Forbidden` error when attempting to list `persistentvolumeclaims`. Before the upgrade, these actions were permitted, and `oc auth can-i list persistentvolumeclaims -n confirms that the user should have access. However, API requests are being executed as `system:anonymous`, resulting in a permission denial.

**Issue Details:**
- Example Namespace: `b01faf-prod`
- Affected Resource: `persistentvolumeclaims`
- Command Check:
  ```sh
  oc auth can-i list persistentvolumeclaims -n <example>
  ```

- Error Message:
  ```json
  {"apiVersion":"v1","code":403,"details":{"kind":"persistentvolumeclaims"},"kind":"Status","level":"error","message":"persistentvolumeclaims is forbidden: User \"system:anonymous\" cannot list resource \"persistentvolumeclaims\" in API group \"\" in the namespace \"b01faf-prod\"","metadata":{},"reason":"Forbidden","status":"Failure","timestamp":"2025-02-06T21:25:43.110Z"}
  ```

**Requested Actions:**
- Review and update role bindings to ensure users retain necessary permissions post-upgrade.

**Comment by Kolezhanchik** [comment]
working with last permissions update 
<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9EQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8a4613907b9bdb16c233c273ab16277ecb3a7f8/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Which level was it fixed at?
On Prod it can't be seen now:
<img width="1075" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhMQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d00c5a8c2b24253a20c678dc5ff2dfa38855fd0/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
it was fixed on all levels, but on prod tokens are not added to vault, please, test on `test` level and after your approval we will add tokens on `prod`

**Comment by funtigr** [comment]
Hm, can't see it on Dev on this licencePlate:
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhPQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfdd60e9e4c3e83e5f538e7a611fa452b7370b4c/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
most of all it is because there is no such LP in Openshift

**Comment by funtigr** [comment]
I added a PVC to the e3913e-prod, but it's still not visible on dev:
<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZQQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d303563d4ada7977068aae9261141d29afcb177/image.png" alt="image.png" />
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJQQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9723bc29a1c580d7ba7011019355517fad34f10/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
<img width="1377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05QQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7a8e03c3cad06dcd5bdcea71bf5dfcfe8219fcc/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
for 

```
  if (!(IS_PROD || IS_TEST)) {
    licencePlate = 'b01faf';
    cluster = 'KLAB';
  }
```
<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlQQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a83a0dfaa714502c843d7a11ccfa1a290d820343/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Works as expected, as seen from the screenshot in the previous comment.
